
book:
  abstract: |
      This book gives readers an overview of the breadth of the field of psychological assessment and various assessment approaches, applying a scientific perspective to the principles of psychological assessment.
      The goal of the book is to help researchers and clinicians learn to think critically about assessments so they can better develop, evaluate, administer, score, integrate, and interpret psychological assessments.
