project:
  type: book

book:
  title: "Principles of Psychological Assessment: With Applied Examples in R"
  subtitle: "Version 1.0.8"
  author: "Isaac T. Petersen"
  date: today
  cover-image: images/cover.png
  cover-image-alt: "Principles of Psychological Assessment Book Cover"
  sharing: [twitter, facebook, linkedin]
  doi: 10.25820/work.007199
  isbn: "9780984037827"
  keyword: psychological assessment, R software, psychometrics, measurement, reliability, validity
  license: "CC BY"
  reader-mode: true
  page-footer:
    left: |
      "Principles of Psychological Assessment: With Applied Examples in R" was written by <a href="https://psychology.uiowa.edu/people/isaac-petersen">Isaac T. Petersen</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  favicon: images/logo.png
  twitter-card: true
  open-graph: true
  site-url: https://isaactpetersen.github.io/Principles-Psychological-Assessment
  repo-url: https://github.com/isaactpetersen/Principles-Psychological-Assessment
  repo-branch: main
  repo-actions: [edit, source, issue]
  google-analytics: G-WZJ45RB1K4
  chapters:
    - index.qmd
    - intro.qmd
    - scores-scales.qmd
    - constructs.qmd
    - reliability.qmd
    - validity.qmd
    - generalizability-theory.qmd
    - structural-equation-modeling.qmd
    - item-response-theory.qmd
    - prediction.qmd
    - clinical-actuarial-judgment.qmd
    - clinical-assessment.qmd
    - evidence-based-assessment.qmd
    - ethics.qmd
    - factor-analysis-pca.qmd
    - intellectual-assessment.qmd
    - test-bias.qmd
    - interview-dsm.qmd
    - objective-personality-testing.qmd
    - projective-personality-testing.qmd
    - psychophysiological-measures.qmd
    - computerized-adaptive-testing.qmd
    - behavioral-assessment.qmd
    - repeated-assessment.qmd
    - cognitive-assessment.qmd
    - diversity.qmd
    - reproducibility.qmd
    - references.qmd

bibliography: [references.bib, packages.bib]
csl: apa.csl

format:
  html:
    highlight-style: a11y
    theme:
      light: [cosmo, fonts/css/lora.css]
      dark: [cosmo, fonts/css/lora.css, theme-dark.scss]
    mainfont: Lora #gfonts::setup_font("lora", output_dir = "./fonts/"); gfonts::get_all_fonts()
    code-link: true
    number-sections: true
    code-fold: show
    code-line-numbers: true
    toc: true
    toc-depth: 5
    execute:
      error: true
      message: false
      warning: false
    keep-md: true
    link-external-newwindow: true
    embed-resources: false
    anchor-sections: true
    df-print: paged
    comments:
      hypothesis:
        theme: classic
        openSidebar: false
        showHighlights: whenSidebarOpen
      giscus:
        repo: isaactpetersen/Principles-Psychological-Assessment
        repo-id: MDEwOlJlcG9zaXRvcnkzNzIwMjExNjg=
        category: Chapter Comments
        category-id: DIC_kwDOFiyXsM4CzZAv
        mapping: pathname
        reactions-enabled: false
        loading: lazy
        input-position: top
    #include-in-header:
    #  - "includes/google_analytics.html"
    include-before-body:
      - "includes/open-review.html"
    include-after-body:
    #  - "includes/disqus.html"
      - "includes/email_submit.html"
    #  - "includes/footer.html"
    license: CC BY
    author-meta: "Isaac T. Petersen"
    date-meta: today
  pdf:
    documentclass: krantz
    classoption: krantz2
    link-citations: true
    colorlinks: true
    keep-tex: true
    lot: true
    lof: true
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    execute:
      error: true
      message: false
      warning: false
    cite-method: biblatex
    biblatexoptions:
      - "backend=biber"
      - "backref=true"
      - "style=apa"
      - "language=american"
  epub:
    execute:
      error: true
      message: false
      warning: false

lightbox: 
  match: auto
