on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish to HTML

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # update
        with:
          lfs: true  # This ensures that Git LFS files are pulled
        
      - name: Checkout LFS objects
        run: git lfs checkout
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2 # update
        
      - name: Session info
        run: Rscript -e 'sessionInfo()'
        
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2 # update
        
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libharfbuzz-dev \
            libfribidi-dev
        
      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@v2 # update
        
      - name: Install additional LaTeX packages
        run: |
          #tlmgr install url
          #tlmgr install underscore
          tlmgr update --self
          tlmgr install \
            collectbox \
            titling \
            framed \
            mdframed \
            ulem \
            hyperref \
            url \
            underscore \
            xcolor \
            csquotes
        
      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2 # update

      - name: Install archived packages
        run: |
         Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/gtheory/gtheory_0.1.2.tar.gz")'
        
      #- name: Install remote packages
      #  run: |
      #   Rscript -e 'remotes::install_github("DevPsyLab/petersenlab")'
        
      #- name: Install cmdstan
      #  run: |
      #    cmdstanr::check_cmdstan_toolchain(fix = TRUE)
      #    cmdstanr::install_cmdstan(cores = 2)
      #  shell: Rscript {0}
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2 # update
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2 # update
        env:
          QUARTO_PROFILE: html
        with:
          to: html # can specify a particular output format
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2 # update
        with:
          target: gh-pages
          render: false # renders in previous step, so don't render again
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in workspace
        if: always()
        run: |
          ls -lh
          find . -type f
        
      - name: Archive production artifacts
        if: always() # ensures it runs even if previous steps fail
        uses: actions/upload-artifact@v4 # update
        with:
          name: _book
          path: |
            _book/
            *.toc
            *.out
            *.aux
            *.log
            *.tex
            *.md
            *.log
            *.bbl
            *.blg
            *.txt
